<!DOCTYPE html>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>    
    <head>        
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content="nookandcove">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="resources/images/ico/favicon.ico" type="image/x-icon"/>    
	</head>	
		<body>		
		<div id="mainframe" class="section-content"> <div class="container"> <div class="row top_adjustment_10"> <div class="col-md-1 col-sm-1"> </div> <div class="col-md-10 col-sm-10"> <div class="service-item"> <div class="service-description text-center">
	    <div class="regi_privacy_main_bold_hd"><h2>TERMS OF SERVICE</h2></div>
	    <div class="regi_privacy_normal_text_dsp"><p>PLEASE READ THE FOLLOWING TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING OUR SITES AND OUR SERVICES, YOU HEREBY AGREE TO BE BOUND BY THE TERMS AND ALL TERMS INCORPORATED HEREIN BY REFERENCE.  IT IS THE RESPONSIBILITY OF YOU, THE USER, CUSTOMER, OR PROSPECTIVE CUSTOMER TO READ THE TERMS AND CONDITIONS BEFORE PROCEEDING TO USE THIS SITE.  IF YOU DO NOT EXPRESSLY AGREE TO ALL OF THE TERMS AND CONDITIONS, THEN PLEASE DO NOT ACCESS OR USE OUR SITES OR OUR SERVICES.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>ACCEPTANCE OF TERMS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>The following Terms of Service (the "TOS") is a legally binding agreement that shall govern the relationship with our users and others which may interact or interface with Nook and Cove LLC, also known as Nook + Cove, located at 1120 Ashley Lane, Inverness, Illinois 60010 and our subsidiaries and affiliates, in association with the use of the Nook + Cove website, which includes www.nookandcove.com, (the "Site") and its Services, which shall be defined below.</p></div>
	    	    
	    <div class="regi_privacy_sub_bold_hd"><h3>DESCRIPTION OF WEBSITE SERVICES OFFERED</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>The Site is an e-commerce website which has the following description:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook + Cove is a platform where people seeking interior design services ("Clients" or "Users") answer a questionnaire, interact with a designer, and obtain custom concepts, renderings and revisions based on the design package they have chosen. Clients are also able to purchase merchandise from their custom shopping lists through the Site.</p></div>	    
	    <div class="regi_privacy_normal_text_dsp"><p>Any and all visitors to our site, despite whether they are registered or not, shall be deemed as "users" of the herein contained Services provided for the purpose of this TOS. Once an individual register's for our Services, through the process of creating an account, the user shall then be considered a "member." The user and/or member acknowledges and agrees that the Services provided and made available through our website and applications, which may include some mobile applications and that those applications may be made available on various social media networking sites and numerous other platforms and downloadable programs, are the sole property of Nook and Cove LLC. At its discretion, Nook and Cove LLC may offer additional website Services and/or products, or update, modify or revise any current content and Services, and this Agreement shall apply to any and all additional Services and/or products and any and all updated, modified or revised Services unless otherwise stipulated. Nook and Cove LLC does hereby reserve the right to cancel and cease offering any of the aforementioned Services and/or products.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>You, as the end user and/or member, acknowledge, accept and agree that Nook and Cove LLC shall not be held liable for any such updates, modifications, revisions, suspensions or discontinuance of any of our Services and/or products. Your continued use of the Services provided, after such posting of any updates, changes, and/or modifications shall constitute your acceptance of such updates, changes and/or modifications, and as such, frequent review of this Agreement and any and all applicable terms and policies should be made by you to ensure you are aware of all terms and policies currently in effect. Should you not agree to the updated, revised or modified terms, you must stop using the provided Services forthwith.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Furthermore, the user and/or member understands, acknowledges and agrees that the Services offered shall be provided "AS IS" and as such Nook and Cove LLC shall not assume any responsibility or obligation for the timeliness, missed delivery, deletion and/or any failure to store user content, communication or personalization settings.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>REGISTRATION</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>To register and become a "member" of the Site, you must be at least 18 years of age to enter into and form a legally binding contract. In addition, you must be in good standing and not an individual that has been previously barred from receiving Nook + Cove's Services under the laws and statutes of the United States or other applicable jurisdiction.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>When you register, Nook + Cove may collect information such as your name, e-mail address, birth date, gender, and mailing address. Once you register with Nook + Cove and sign in to our Services, you are no longer anonymous to us. Furthermore, the registering party hereby acknowledges, understands and agrees to:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) furnish factual, correct, current and complete information with regards to yourself as may be requested by the data registration process, and</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) maintain and promptly update your registration and profile information in an effort to maintain accuracy and completeness at all times.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>If anyone knowingly provides any information of a false, untrue, inaccurate or incomplete nature, Nook and Cove LLC will have sufficient grounds and rights to suspend or terminate the member in violation of this aspect of the Agreement, and as such refuse any and all current or future use of Nook and Cove LLC Services, or any portion thereof.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>PRIVACY POLICY</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Every member's registration data and various other personal information are strictly protected by the Nook and Cove LLC Online Privacy Policy (see the full Privacy Policy at <a href="https://www.nookandcove.com/nc/privacyPolicy" style="text-decoration: none; color: #1467bc;">https://www.nookandcove.com/privacypolicy</a>). As a member, you herein consent to the collection and use of the information provided, including the transfer of information within the United States and/or other countries for storage, processing or use by Nook and Cove LLC and/or our subsidiaries and affiliates.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>MEMBER ACCOUNT, USERNAME, PASSWORD AND SECURITY</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>When you set up an account, you are the sole authorized user of your account. You shall be responsible for maintaining the secrecy and confidentiality of your password and for all activities that transpire on or within your account. It is your responsibility for any act or omission of any user(s) that access your account information that, if undertaken by you, would be deemed a violation of the TOS. It shall be your responsibility to notify Nook and Cove LLC immediately if you notice any unauthorized access or use of your account or password or any other breach of security. Nook and Cove LLC shall not be held liable for any loss and/or damage arising from any failure to comply with this term and/or condition of the TOS.</p></div>	    
	    <div class="regi_privacy_sub_bold_hd"><h3>CONDUCT</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>As a user or member of the Site, you herein acknowledge, understand and agree that all information, text, photographs, messages, tags or any other content, whether it is publicly or privately posted and/or transmitted, is the expressed sole responsibility of the individual from whom the content originated. In short, this means that you are solely responsible for any and all content posted, uploaded, emailed, transmitted or otherwise made available by way of the Nook + Cove Services, and as such, we do not guarantee the accuracy, integrity or quality of such content. It is expressly understood that by use of our Services, you may be exposed to content including, but not limited to, any errors or omissions in any content posted, and/or any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted or otherwise made available by Nook + Cove. Furthermore, you herein agree not to make use of Nook and Cove LLC's Services for the purpose of:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) uploading, posting, emailing, transmitting, or otherwise making available any content that shall be deemed unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or invasive of another's privacy or which is hateful, and/or racially, ethnically, or otherwise objectionable;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) causing harm to minors in any manner whatsoever;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) impersonating any individual or entity, including, but not limited to, any Nook + Cove officials, forum leaders, guides or hosts or falsely stating or otherwise misrepresenting any affiliation with an individual or entity;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) forging captions, headings or titles or otherwise offering any content that you personally have no right to pursuant to any law nor having any contractual or fiduciary relationship with;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>e) uploading, posting, emailing, transmitting or otherwise offering any such content that may infringe upon any patent, copyright, trademark, or any other proprietary or intellectual rights of any other party;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>f) uploading, posting, emailing, transmitting or otherwise offering any content that you do not personally have any right to offer pursuant to any law or in accordance with any contractual or fiduciary relationship;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>g) uploading, posting, emailing, transmitting, or otherwise offering any unsolicited or unauthorized advertising, promotional flyers, "junk mail," "spam," or any other form of solicitation, except in any such areas that may have been designated for such purpose;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>h) uploading, posting, emailing, transmitting, or otherwise offering any source that may contain a software virus or other computer code, any files and/or programs which have been designed to interfere, destroy and/or limit the operation of any computer software, hardware, or telecommunication equipment;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>i) disrupting the normal flow of communication, or otherwise acting in any manner that would negatively affect other users' ability to participate in any real time interactions;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>j) interfering with or disrupting any Nook and Cove LLC Services, servers and/or networks that may be connected or related to our website, including, but not limited to, the use of any device software and/or routine to bypass the robot exclusion headers;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>k) intentionally or unintentionally violating any local, state, federal, national or international law, including, but not limited to, rules, guidelines, and/or regulations decreed by the U.S. Securities and Exchange Commission, in addition to any rules of any nation or other securities exchange, that would include without limitation, the New York Stock Exchange, the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>l) providing informational support or resources, concealing and/or disguising the character, location, and or source to any organization delegated by the United States government as a "foreign terrorist organization" in accordance to Section 219 of the Immigration Nationality Act;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>m) "stalking" or with the intent to otherwise harass another individual; and/or</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>n) collecting or storing of any personal data relating to any other member or user in connection with the prohibited conduct and/or activities which have been set forth in the aforementioned paragraphs.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook And Cove LLC herein reserves the right to pre-screen, refuse and/or delete any content currently available through our Services. In addition, we reserve the right to remove and/or delete any such content that would violate the TOS or which would otherwise be considered offensive to other visitors, users and/or members.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook And Cove LLC herein reserves the right to access, preserve and/or disclose member account information and/or content if it is requested to do so by law or in good faith belief that any such action is deemed reasonably necessary for:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) compliance with any legal process;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) enforcement of the TOS;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) responding to any claim that therein contained content is in violation of the rights of any third party;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) responding to requests for customer service; or</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>e) protecting the rights, property or the personal safety of Nook and Cove LLC, its visitors, users and members, including the general public.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook And Cove LLC herein reserves the right to include the use of security components that may permit digital information or material to be protected, and that such use of information and/or material is subject to usage guidelines and regulations established by Nook and Cove LLC or any other content providers supplying content services to Nook and Cove LLC. You are hereby prohibited from making any attempt to override or circumvent any of the embedded usage rules in our Services. Furthermore, unauthorized reproduction, publication, distribution, or exhibition of any information or materials supplied by our Services, despite whether done so in whole or in part, is expressly prohibited.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>CAUTIONS FOR GLOBAL USE AND EXPORT AND IMPORT COMPLIANCE</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Due to the global nature of the internet, through the use of our network you hereby agree to comply with all local rules relating to online conduct and that which is considered acceptable content. Uploading, posting and/or transferring of software, technology and other technical data may be subject to the export and import laws of the United States and possibly other countries. Through the use of our network, you thus agree to comply with all applicable export and import laws, statutes and regulations, including, but not limited to, the Export Administration Regulations (http://www.access.gpo.gov/bis/ear/ear_data.html), as well as the sanctions control program of the United States (<a href="http://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx" style="text-decoration: none; color: #1467bc;">http://www.treasury.gov/resourcecenter/sanctions/Programs/Pages/Programs.aspx</a>).</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Furthermore, you state and pledge that you:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) are not on the list of prohibited individuals which may be identified on any government export exclusion report (<a href="http://www.bis.doc.gov/complianceandenforcement/liststocheck.htm" style="text-decoration: none; color: #1467bc;">http://www.bis.doc.gov/complianceandenforcement/liststocheck.htm</a>) nor a member of any other government which may be part of an export-prohibited country identified in applicable export and import laws and regulations;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) agree not to transfer any software, technology or any other technical data through the use of our network Services to any export-prohibited country;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) agree not to use our website network Services for any military, nuclear, missile, chemical or biological weaponry end uses that would be a violation of the U.S. export laws; and</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) agree not to post, transfer nor upload any software, technology or any other technical data which would be in violation of the U.S. or other applicable export and/or import laws.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>CONTENT PLACED OR MADE AVAILABLE FOR COMPANY SERVICES</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook and Cove LLC shall not lay claim to ownership of any content submitted by any visitor, member, or user, nor make such content available for inclusion on our website Services. Therefore, you hereby grant and allow for Nook and Cove LLC the below listed worldwide, royalty-free and non-exclusive licenses, as applicable:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) The content submitted or made available for inclusion on the publicly accessible areas of Nook and Cove LLC's sites, the license provided to permit to use, distribute, reproduce, modify, adapt, publicly perform and/or publicly display said Content on our network Services is for the sole purpose of providing and promoting the specific area to which this content was placed and/or made available for viewing. This license shall be available so long as you are a member of Nook and Cove LLC's sites, and shall terminate at such time when you elect to discontinue your membership.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) Photos, audio, video and/or graphics submitted or made available for inclusion on the publicly accessible areas of Nook and Cove LLC's sites, the license provided to permit to use, distribute, reproduce, modify, adapt, publicly perform and/or publicly display said Content on our network Services are for the sole purpose of providing and promoting the specific area in which this content was placed and/or made available for viewing. This license shall be available so long as you are a member of Nook and Cove LLC's sites and shall terminate at such time when you elect to discontinue your membership.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) For any other content submitted or made available for inclusion on the publicly accessible areas of Nook and Cove LLC's sites, the continuous, binding and completely sub licensable license which is meant to permit to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform and/or publicly display said content, whether in whole or in part, and the incorporation of any such Content into other works in any arrangement or medium current used or later developed. Those areas which may be deemed "publicly accessible" areas of Nook and Cove LLC's sites are those such areas of our network properties which are meant to be available to the general public, and which would include message boards and groups that are openly available to both users and members.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>CONTRIBUTIONS TO COMPANY WEBSITE</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook And Cove LLC provides an area for our users and members to contribute feedback to our website. When you submit ideas, documents, suggestions and/or proposals ("Contributions") to our site, you acknowledge and agree that:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) your contributions do not contain any type of confidential or proprietary information;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) Nook + Cove shall not be liable or under any obligation to ensure or maintain confidentiality, expressed or implied, related to any Contributions;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) Nook + Cove shall be entitled to make use of and/or disclose any such Contributions in any such manner as they may see fit;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) the contributor's Contributions shall automatically become the sole property of Nook + Cove; and</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>e) Nook + Cove is under no obligation to either compensate or provide any form of reimbursement in any manner or nature.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>INDEMNITY</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>All users and/or members herein agree to insure and hold Nook and Cove LLC, our subsidiaries, affiliates, agents, employees, officers, partners and/or licensors blameless or not liable for any claim or demand, which may include, but is not limited to, reasonable attorney fees made by any third party which may arise from any content a member or user of our site may submit, post, modify, transmit or otherwise make available through our Services, the use of Nook + Cove Services or your connection with these Services, your violations of the Terms of Service and/or your violation of any such rights of another person.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>COMMERCIAL REUSE OF SERVICES</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>The member or user herein agrees not to replicate, duplicate, copy, trade, sell, resell nor exploit for any commercial reason any part, use of, or access to Nook + Cove's sites.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>USE AND STORAGE GENERAL PRACTICES</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>You herein acknowledge that Nook and Cove LLC may set up any such practices and/or limits regarding the use of our Services, without limitation of the maximum number of days that any email, message posting or any other uploaded content shall be retained by Nook and Cove LLC, nor the maximum number of email messages that may be sent and/or received by any member, the maximum volume or size of any email message that may be sent from or may be received by an account on our Service, the maximum disk space allowable that shall be allocated on Nook and Cove LLC's servers on the member's behalf, and/or the maximum number of times and/or duration that any member may access our Services in a given period of time. In addition, you also agree that Nook and Cove LLC has absolutely no responsibility or liability for the removal or failure to maintain storage of any messages and/or other communications or content maintained or transmitted by our Services. You also herein acknowledge that we reserve the right to delete or remove any account that is no longer active for an extended period of time. Furthermore, Nook and Cove LLC shall reserve the right to modify, alter and/or update these general practices and limits at our discretion.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>MODIFICATIONS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook and Cove LLC shall reserve the right at any time it may deem fit, to modify, alter and or discontinue, whether temporarily or permanently, our service, or any part thereof, with or without prior notice. In addition, we shall not be held liable to you or to any third party for any such alteration, modification, suspension and/or discontinuance of our Services, or any part thereof.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>TERMINATION</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>As a member of www.nookandcove.com, you may cancel or terminate your account, associated email address and/or access to our Services by submitting a cancellation or termination request to <font color="#1467bc" style="text-decoration: underline;">hello@nookandcove.com</font>. As a member, you agree that Nook and Cove LLC may, without any prior written notice, immediately suspend, terminate, discontinue and/or limit your account, any email associated with your account, and access to any of our Services. The cause for such termination, discontinuance, suspension and/or limitation of access shall include, but is not limited to:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) any breach or violation of our TOS or any other incorporated agreement, regulation and/or guideline;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) by way of requests from law enforcement or any other governmental agencies;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) the discontinuance, alteration and/or material modification to our Services, or any part thereof;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) unexpected technical or security issues and/or problems;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>e) any extended periods of inactivity;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>f) any engagement by you in any fraudulent or illegal activities; and/or</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>g) the nonpayment of any associated fees that may be owed by you in connection with your www.nookandcove.com account Services.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Furthermore, you herein agree that any and all terminations, suspensions, discontinuances, and or limitations of access for cause shall be made at our sole discretion and that we shall not be liable to you or any other third party with regards to the termination of your account, associated email address and/or access to any of our Services.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>The termination of your account with www.nookandcove.com shall include any and/or all of the following:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) the removal of any access to all or part of the Services offered within www.nookandcove.com;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) the deletion of your password and any and all related information, files, and any such content that may be associated with or inside your account, or any part thereof; and</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) the barring of any further use of all or part of our Services.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>ADVERTISERS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Any correspondence or business dealings with, or the participation in any promotions of, advertisers located on or through our Services, which may include the payment and/or delivery of such related goods and/or Services, and any such other term, condition, warranty and/or representation associated with such dealings, are and shall be solely between you and any such advertiser. Moreover, you herein agree that Nook and Cove LLC shall not be held responsible or liable for any loss or damage of any nature or manner incurred as a direct result of any such dealings or as a result of the presence of such advertisers on our website.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>LINKS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Either Nook and Cove LLC or any third parties may provide links to other websites and/or resources. Thus, you acknowledge and agree that we are not responsible for the availability of any such external sites or resources, and as such, we do not endorse nor are we responsible or liable for any content, products, advertising or any other materials, on or available from such third party sites or resources. Furthermore, you acknowledge and agree that Nook and Cove LLC shall not be responsible or liable, directly or indirectly, for any such damage or loss which may be a result of, caused or allegedly to be caused by or in connection with the use of or the reliance on any such content, goods or Services made available on or through any such site or resource.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>PROPRIETARY RIGHTS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>You do hereby acknowledge and agree that Nook and Cove LLC's Services and any essential software that may be used in connection with our Services ("Software") shall contain proprietary and confidential material that is protected by applicable intellectual property rights and other laws. Furthermore, you herein acknowledge and agree that any Content which may be contained in any advertisements or information presented by and through our Services or by advertisers is protected by copyrights, trademarks, patents or other proprietary rights and laws. Therefore, except for that which is expressly permitted by applicable law or as authorized by Nook and Cove LLC or such applicable licensor, you agree not to alter, modify, lease, rent, loan, sell, distribute, transmit, broadcast, publicly perform and/or created any plagiaristic works which are based on Nook and Cove LLC Services (e.g. Content or Software), in whole or part. Nook and Cove LLC herein has granted you personal, non-transferable and non-exclusive rights and/or license to make use of the object code or our Software on a single computer, as long as you do not, and shall not, allow any third party to duplicate, alter, modify, create or plagiarize work from, reverse engineer, reverse assemble or otherwise make an attempt to locate or discern any source code, sell, assign, sublicense, grant a security interest in and/or otherwise transfer any such right in the Software. Furthermore, you do herein agree not to alter or change the Software in any manner, nature or form, and as such, not to use any modified versions of the Software, including and without limitation, for the purpose of obtaining unauthorized access to our Services.  Lastly, you also agree not to access or attempt to access our Services through any means other than through the interface which is provided by Nook and Cove LLC for use in accessing our Services.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>WARRANTY DISCLAIMERS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>YOU HEREIN EXPRESSLY ACKNOWLEDGE AND AGREE THAT:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) THE USE OF NOOK AND COVE LLC SERVICES AND SOFTWARE ARE AT THE SOLE RISK BY YOU. OUR SERVICES AND SOFTWARE SHALL BE PROVIDED ON AN "AS IS" AND/OR "AS AVAILABLE" BASIS. NOOK AND COVE LLC AND OUR SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF ANY KIND WHETHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) NOOK AND COVE LLC AND OUR SUBSIDIARIES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS MAKE NO SUCH WARRANTIES THAT (i) NOOK AND COVE LLC SERVICES OR SOFTWARE WILL MEET YOUR REQUIREMENTS; (ii)NOOK AND COVE LLC SERVICES OR SOFTWARE SHALL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (iii) THAT SUCH RESULTS WHICH MAY BE OBTAINED FROM THE USE OF THE NOOK AND COVE LLC SERVICES OR SOFTWARE WILL BE ACCURATE OR RELIABLE; (iv) QUALITY OF ANY PRODUCTS, SERVICES, ANY INFORMATION OR OTHER MATERIAL WHICH MAY BE PURCHASED OR OBTAINED BY YOU THROUGH OUR SERVICES OR SOFTWARE WILL MEET YOUR EXPECTATIONS; AND (v) THAT ANY SUCH ERRORS CONTAINED IN THE SOFTWARE SHALL BE CORRECTED.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) ANY INFORMATION OR MATERIAL DOWNLOADED OR OTHERWISE OBTAINED BY WAY OF NOOK AND COVE LLC SERVICES OR SOFTWARE SHALL BE ACCESSED BY YOUR SOLE DISCRETION AND SOLE RISK, AND AS SUCH YOU SHALL BE SOLELY RESPONSIBLE FOR AND HEREBY WAIVE ANY AND ALL CLAIMS AND CAUSES OF ACTION WITH RESPECT TO ANY DAMAGE TO YOUR COMPUTER AND/OR INTERNET ACCESS, DOWNLOADING AND/OR DISPLAYING, OR FOR ANY LOSS OF DATA THAT COULD RESULT FROM THE DOWNLOAD OF ANY SUCH INFORMATION OR MATERIAL.</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) NO ADVICE AND/OR INFORMATION, DESPITE WHETHER WRITTEN OR ORAL, THAT MAY BE OBTAINED BY YOU FROM NOOK AND COVE LLC OR BY WAY OF OR FROM OUR SERVICES OR SOFTWARE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>LIMITATION OF LIABILITY</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>YOU EXPLICITLY ACKNOWLEDGE, UNDERSTAND AND AGREE THAT NOOK AND COVE LLC AND OUR SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY PUNITIVE, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES WHICH MAY BE RELATED TO THE LOSS OF ANY PROFITS, GOODWILL, USE, DATA AND/OR OTHER INTANGIBLE LOSSES, EVEN THOUGH WE MAY HAVE BEEN ADVISED OF SUCH POSSIBILITY THAT SAID DAMAGES MAY OCCUR, AND RESULT FROM:</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>a) THE USE OR INABILITY TO USE OUR SERVICE;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>b) THE COST OF PROCURING SUBSTITUTE GOODS AND SERVICES;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>c) UNAUTHORIZED ACCESS TO OR THE ALTERATION OF YOUR TRANSMISSIONS AND/OR DATA;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>d) STATEMENTS OR CONDUCT OF ANY SUCH THIRD PARTY ON OUR SERVICE;</p></div>
	    <div class="regi_privacy_normal_text_dsp"><p>e) AND ANY OTHER MATTER WHICH MAY BE RELATED TO OUR SERVICE. </p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>RELEASE</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>In the event you have a dispute, you agree to release Nook and Cove LLC (and its officers, directors, employees, agents, parent subsidiaries, affiliates, co-branders, partners and any other third parties) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected or unsuspected, disclosed and undisclosed, arising out of or in any way connected to such dispute.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>SPECIAL ADMONITION RELATED TO FINANCIAL MATTERS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Should you intend to create or to join any service, receive or request any such news, messages, alerts or other information from our Services concerning companies, stock quotes, investments or securities, please review the above Sections Warranty Disclaimers and Limitations of Liability again. In addition, for this particular type of information, the phrase "Let the investor beware" is appropriate. Nook and Cove LLC's content is provided primarily for informational purposes, and no content that shall be provided or included in our Services is intended for trading or investing purposes. Nook and Cove LLC and our licensors shall not be responsible or liable for the accuracy, usefulness or availability of any information transmitted and/or made available by way of our Services, and shall not be responsible or liable for any trading and/or investment decisions based on any such information.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>EXCLUSION AND LIMITATIONS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>THERE ARE SOME JURISDICTIONS WHICH DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OF EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES.  HEREFORE, SOME OF THE ABOVE LIMITATIONS OF SECTIONS WARRANTY DISCLAIMERS AND LIMITATION OF LIABILITY MAY NOT APPLY TO YOU.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>THIRD PARTY BENEFICIARIES</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>You herein acknowledge, understand and agree, unless otherwise expressly provided in this TOS, that there shall be no third-party beneficiaries to this agreement.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>NOTICE</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Nook and Cove LLC may furnish you with notices, including those with regards to any changes to the TOS, including but not limited to email, regular mail, postings on our website Services, or other reasonable means currently known or any which may be herein after developed. Any such notices may not be received if you violate any aspects of the TOS by accessing our Services in an unauthorized manner. Your acceptance of this TOS constitutes your agreement that you are deemed to have received any and all notices that would have been delivered had you accessed our Services in an authorized manner.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>TRADEMARK INFORMATION</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>You herein acknowledge, understand and agree that all of the Nook and Cove LLC trademarks, copyright, trade name, service marks, and other Nook and Cove LLC logos and any brand features, and/or product and service names are trademarks and as such, are and shall remain the property of Nook and Cove LLC. You herein agree not to display and/or use in any manner the Nook and Cove LLC logo or marks without obtaining Nook and Cove LLC's prior written consent.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>GENERAL INFORMATION</h3></div>
	    <div class="regi_privacy_sub_bold_hd"><h3>ENTIRE AGREEMENT</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>This TOS constitutes the entire agreement between you and Nook and Cove LLC and shall govern the use of our Services, superseding any prior version of this TOS between you and us with respect to Nook and Cove LLC Services. You may also be subject to additional terms and conditions that may apply when you use or purchase certain other Nook and Cove LLC Services, affiliate Services, third-party content or third-party software.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>CHOICE OF LAW AND FORUM</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>It is at the mutual agreement of both you and Nook and Cove LLC with regard to the TOS that the relationship between the parties shall be governed by the laws of the state of Illinois without regard to its conflict of law provisions and that any and all claims, causes of action and/or disputes, arising out of or relating to the TOS, or the relationship between you and Nook And Cove LLC, shall be filed within the courts having jurisdiction within the County of Cook, Illinois or the U.S. District Court located in said state. You and Nook and Cove LLC agree to submit to the jurisdiction of the courts as previously mentioned, and agree to waive any and all objections to the exercise of jurisdiction over the parties by such courts and to venue in such courts.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>WAIVER AND SEVERABILITY OF TERMS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>At any time, should Nook and Cove LLC fail to exercise or enforce any right or provision of the TOS, such failure shall not constitute a waiver of such right or provision. If any provision of this TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>STATUTE OF LIMITATIONS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>You acknowledge, understand and agree that regardless of any statute or law to the contrary, any claim or action arising out of or related to the use of our Services or the TOS must be filed within 1 year after said claim or cause of action arose or shall be forever barred.</p></div>
	    
	    <div class="regi_privacy_sub_bold_hd"><h3>VIOLATIONS</h3></div>
	    <div class="regi_privacy_normal_text_dsp"><p>Please report any and all violations of this TOS to Nook and Cove LLC as follows:</p></div>
	    
	    <table> <tr><td class="regi_privacy_td_sub_bold_hd">Email:</td> <td class="regi_privacy_td_normal_text_dsp"><font color="#1467bc" style="text-decoration: underline;">hello@nookandcove.com</font></td></tr> </table>	    
	    <table> <tr><td class="regi_privacy_td_sub_bold_hd">Telephone Number:</td> <td class="regi_privacy_td_normal_text_dsp">888.580.2030</td></tr> </table>	    
	    <table> <tr><td class="regi_privacy_td_sub_bold_hd">Mailing Address:</td> <td class="regi_privacy_td_normal_text_dsp">Nook and Cove LLC <br>1120 Ashle </table>	    
	    <table class="top_adjustment_10"> <tr><td class="regi_privacy_td_normal_text_dsp1">THIS TERMS OF SERVICE AGREEMENT IS EFFECTIVE AS OF 05/01/2017.</td></tr> </table> </div>
	    </div> </div> <div class="col-md-1 col-sm-1"> </div> </div> </div> </div>		
		</body>
</html>